name: pull-request
on:
  pull_request
jobs:
  repo:
    name: baixar todo codigo do git e cachear
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: install java
        uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'
      - run: mvn package