name: pull-request
on:
  push:
    paths:
      - 'management/**'
jobs:
  repo:
    name: baixar todo codigo do git e cachear
    runs-on: ubuntu-latest
    env:
      working-directory: ./management
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: install java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: mvn package
        working-directory: ${{env.working-directory}}
